Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: true
        price:
            type: integer
            nullable: true
            options:
                unsigned: false
        reference:
            type: string
            nullable: true
            length: 255
            options:
                fixed: true
    lifecycleCallbacks: {  }
